<?php

return [
    // Dashboards
    [
        'id'        => 'dashboards',
        'title'     => __('sneat.dashboards'),
        'icon'      => Dcat\Admin\DcatIcon::HOME_CIRCLE(),
        'uri'       => '',
        'parent_id' => 0,
    ],
    [
        'id'        => 'analytic',
        'title'     => __('sneat.analytics'),
        'icon'      => Dcat\Admin\DcatIcon::HOME_CIRCLE(),
        'uri'       => admin_route(App\Enums\RouteSneat::DASHBOARD_ANALYTIC()),
        'parent_id' => 'dashboards',
    ],

    // Components
    [
        'id'        => 'components',
        'title'     => __('sneat.components'),
        'icon'      => Dcat\Admin\DcatIcon::HOME_CIRCLE(),
        'uri'       => '',
        'parent_id' => 0,
    ],
    [
        'id'        => 'accordion',
        'title'     => __('sneat.accordion'),
        'icon'      => Dcat\Admin\DcatIcon::HOME_CIRCLE(),
        'uri'       => admin_route(App\Enums\RouteSneat::COMPONENTS_ACCORDION()),
        'parent_id' => 'components',
    ],
    [
        'id'        => 'alerts',
        'title'     => __('sneat.alerts'),
        'icon'      => Dcat\Admin\DcatIcon::HOME_CIRCLE(),
        'uri'       => admin_route(App\Enums\RouteSneat::COMPONENTS_ALERTS()),
        'parent_id' => 'components',
    ],
    [
        'id'        => 'check-and-radio',
        'title'     => __('sneat.check_and_radio'),
        'icon'      => Dcat\Admin\DcatIcon::HOME_CIRCLE(),
        'uri'       => admin_route(App\Enums\RouteSneat::COMPONENTS_CHECK_AND_RADIO()),
        'parent_id' => 'components',
    ],
    [
        'id'        => 'dropdown',
        'title'     => __('sneat.dropdown'),
        'icon'      => Dcat\Admin\DcatIcon::HOME_CIRCLE(),
        'uri'       => admin_route(App\Enums\RouteSneat::COMPONENTS_DROPDOWN()),
        'parent_id' => 'components',
    ],
    [
        'id'        => 'progress',
        'title'     => __('sneat.progress'),
        'icon'      => Dcat\Admin\DcatIcon::HOME_CIRCLE(),
        'uri'       => admin_route(App\Enums\RouteSneat::COMPONENTS_PROGRESS()),
        'parent_id' => 'components',
    ],
    [
        'id'        => 'tip-and-popover',
        'title'     => __('sneat.tip_and_popover'),
        'icon'      => Dcat\Admin\DcatIcon::HOME_CIRCLE(),
        'uri'       => admin_route(App\Enums\RouteSneat::COMPONENTS_TIP_AND_POPOVER()),
        'parent_id' => 'components',
    ],
    [
        'id'        => 'toastr',
        'title'     => __('sneat.toastr'),
        'icon'      => Dcat\Admin\DcatIcon::HOME_CIRCLE(),
        'uri'       => admin_route(App\Enums\RouteSneat::COMPONENTS_TOASTR()),
        'parent_id' => 'components',
    ],
    [
        'id'        => 'tabs',
        'title'     => __('sneat.tabs'),
        'icon'      => Dcat\Admin\DcatIcon::HOME_CIRCLE(),
        'uri'       => admin_route(App\Enums\RouteSneat::COMPONENTS_TABS()),
        'parent_id' => 'components',
    ],
    [
        'id'        => 'modal',
        'title'     => __('sneat.modals'),
        'icon'      => Dcat\Admin\DcatIcon::HOME_CIRCLE(),
        'uri'       => admin_route(App\Enums\RouteSneat::COMPONENTS_MODAL()),
        'parent_id' => 'components',
    ],
    [
        'id'        => 'cards',
        'title'     => __('sneat.cards'),
        'icon'      => Dcat\Admin\DcatIcon::HOME_CIRCLE(),
        'uri'       => admin_route(App\Enums\RouteSneat::COMPONENTS_CARDS()),
        'parent_id' => 'components',
    ],
    [
        'id'        => 'markdown',
        'title'     => __('sneat.markdown'),
        'icon'      => Dcat\Admin\DcatIcon::HOME_CIRCLE(),
        'uri'       => admin_route(App\Enums\RouteSneat::COMPONENTS_MARKDOWN()),
        'parent_id' => 'components',
    ],
    [
        'id'        => 'charts',
        'title'     => __('sneat.charts'),
        'icon'      => Dcat\Admin\DcatIcon::HOME_CIRCLE(),
        'uri'       => admin_route(App\Enums\RouteSneat::COMPONENTS_CHARTS()),
        'parent_id' => 'components',
    ],
    [
        'id'        => 'table',
        'title'     => __('sneat.table'),
        'icon'      => Dcat\Admin\DcatIcon::HOME_CIRCLE(),
        'uri'       => admin_route(App\Enums\RouteSneat::COMPONENTS_TABLE()),
        'parent_id' => 'components',
    ],
    [
        'id'        => 'loading',
        'title'     => __('sneat.loading'),
        'icon'      => Dcat\Admin\DcatIcon::HOME_CIRCLE(),
        'uri'       => admin_route(App\Enums\RouteSneat::COMPONENTS_LOADING()),
        'parent_id' => 'components',
    ],

    // Grids
    [
        'id'        => 'grids',
        'title'     => __('sneat.grids'),
        'icon'      => Dcat\Admin\DcatIcon::HOME_CIRCLE(),
        'uri'       => '',
        'parent_id' => 0,
    ],
    [
        'id'        => 'grid-custon',
        'title'     => __('sneat.custon'),
        'icon'      => Dcat\Admin\DcatIcon::HOME_CIRCLE(),
        'uri'       => admin_route(App\Enums\RouteSneat::GRIDS_CUSTOM()),
        'parent_id' => 'grids',
    ],
    [
        'id'        => 'grid',
        'title'     => __('sneat.grid'),
        'icon'      => Dcat\Admin\DcatIcon::HOME_CIRCLE(),
        'uri'       => admin_route(App\Enums\RouteSneat::GRIDS_GRID()),
        'parent_id' => 'grids',
    ],
    [
        'id'        => 'selector',
        'title'     => __('sneat.selector'),
        'icon'      => Dcat\Admin\DcatIcon::HOME_CIRCLE(),
        'uri'       => admin_route(App\Enums\RouteSneat::GRIDS_SELECTOR()),
        'parent_id' => 'grids',
    ],
    [
        'id'        => 'report',
        'title'     => __('sneat.report'),
        'icon'      => Dcat\Admin\DcatIcon::HOME_CIRCLE(),
        'uri'       => admin_route(App\Enums\RouteSneat::GRIDS_REPORT()),
        'parent_id' => 'grids',
    ],
    [
        'id'        => 'fixed-columns',
        'title'     => __('sneat.fixed_columns'),
        'icon'      => Dcat\Admin\DcatIcon::HOME_CIRCLE(),
        'uri'       => admin_route(App\Enums\RouteSneat::GRIDS_FIXED()),
        'parent_id' => 'grids',
    ],
    [
        'id'        => 'fixed-tree',
        'title'     => __('sneat.tree'),
        'icon'      => Dcat\Admin\DcatIcon::HOME_CIRCLE(),
        'uri'       => admin_route(App\Enums\RouteSneat::GRIDS_TREE()),
        'parent_id' => 'grids',
    ],
    // Grids -- Movie
    [
        'id'        => 'grids-movie',
        'title'     => __('sneat.movie'),
        'icon'      => Dcat\Admin\DcatIcon::HOME_CIRCLE(),
        'uri'       => admin_route(App\Enums\RouteSneat::GRIDS_MOVIE_COMING()),
        'parent_id' => 'grids',
    ],

    [
        'id'        => 'grids-movie-coming',
        'title'     => __('sneat.movie'),
        'icon'      => Dcat\Admin\DcatIcon::HOME_CIRCLE(),
        'uri'       => admin_route(App\Enums\RouteSneat::GRIDS_MOVIE_COMING()),
        'parent_id' => 'grids-movie',
    ],
    [
        'id'        => 'grids-movie-in-theatre',
        'title'     => __('sneat.movie_in_theatre'),
        'icon'      => Dcat\Admin\DcatIcon::HOME_CIRCLE(),
        'uri'       => admin_route(App\Enums\RouteSneat::GRIDS_MOVIE_IN_THEATRE()),
        'parent_id' => 'grids-movie',
    ],
    [
        'id'        => 'grids-movie-top',
        'title'     => __('sneat.movie_top'),
        'icon'      => Dcat\Admin\DcatIcon::HOME_CIRCLE(),
        'uri'       => admin_route(App\Enums\RouteSneat::GRIDS_MOVIE_TOP()),
        'parent_id' => 'grids-movie',
    ],
    // Basic
    [
        'id'        => 'basic',
        'title'     => __('sneat.basic'),
        'icon'      => Dcat\Admin\DcatIcon::HOME_CIRCLE(),
        'uri'       => '',
        'parent_id' => 0,
    ],
    [
        'id'        => 'basic-structure',
        'title'     => __('sneat.basic_structure'),
        'icon'      => Dcat\Admin\DcatIcon::HOME_CIRCLE(),
        'uri'       => admin_route(App\Enums\RouteSneat::BASIC()),
        'parent_id' => 'basic',
    ],
    [
        'id'        => 'basic-clients',
        'title'     => __('sneat.clients'),
        'icon'      => Dcat\Admin\DcatIcon::HOME_CIRCLE(),
        'uri'       => admin_route(App\Enums\RouteSneat::CLIENTS()),
        'parent_id' => 'basic',
    ],
    [
        'id'        => 'basic-layout',
        'title'     => __('sneat.layout'),
        'icon'      => Dcat\Admin\DcatIcon::HOME_CIRCLE(),
        'uri'       => admin_route(App\Enums\RouteSneat::LAYOUT()),
        'parent_id' => 'basic',
    ],
    // Forms
    [
        'id'        => 'forms',
        'title'     => __('sneat.forms'),
        'icon'      => Dcat\Admin\DcatIcon::HOME_CIRCLE(),
        'uri'       => '',
        'parent_id' => 0,
    ],
    // Forms - Basic Forms
    [
        'id'        => 'forms-when',
        'title'     => __('sneat.when'),
        'icon'      => Dcat\Admin\DcatIcon::HOME_CIRCLE(),
        'uri'       => admin_route(App\Enums\RouteSneat::FORMS_WHEN()),
        'parent_id' => 'forms',
    ],
    [
        'id'        => 'forms-step',
        'title'     => __('sneat.step'),
        'icon'      => Dcat\Admin\DcatIcon::HOME_CIRCLE(),
        'uri'       => admin_route(App\Enums\RouteSneat::FORMS_STEP()),
        'parent_id' => 'forms',
    ],
    [
        'id'        => 'forms-form',
        'title'     => __('sneat.form'),
        'icon'      => Dcat\Admin\DcatIcon::HOME_CIRCLE(),
        'uri'       => admin_route(App\Enums\RouteSneat::FORMS_FORM()),
        'parent_id' => 'forms',
    ],
    // Forms - Editors
    [
        'id'        => 'forms-editors',
        'title'     => __('sneat.editors'),
        'icon'      => Dcat\Admin\DcatIcon::HOME_CIRCLE(),
        'uri'       => admin_route(App\Enums\RouteSneat::FORMS_EDITORS_MARKDOWN()),
        'parent_id' => 'forms',
    ],
    [
        'id'        => 'forms-editor-markdown',
        'title'     => __('sneat.markdown'),
        'icon'      => Dcat\Admin\DcatIcon::HOME_CIRCLE(),
        'uri'       => admin_route(App\Enums\RouteSneat::FORMS_EDITORS_MARKDOWN()),
        'parent_id' => 'forms-editors',
    ],

    [
        'id'        => 'forms-editor-summercode',
        'title'     => __('sneat.summercode'),
        'icon'      => Dcat\Admin\DcatIcon::HOME_CIRCLE(),
        'uri'       => admin_route(App\Enums\RouteSneat::FORMS_EDITORS_SUMMERCODE()),
        'parent_id' => 'forms-editors',
    ],
    [
        'id'        => 'forms-editor-tinycme',
        'title'     => __('sneat.tinymce'),
        'icon'      => Dcat\Admin\DcatIcon::HOME_CIRCLE(),
        'uri'       => admin_route(App\Enums\RouteSneat::FORMS_EDITORS_TINYMCE()),
        'parent_id' => 'forms-editors',
    ],

];
